plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag

title: hja22 Blog
description:
google_analytics:
show_downloads: false
remote_theme: mmistakes/minimal-mistakes@4.22.0
